# -*- coding: utf-8 -*-
"""Despliegue_BEKP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TT__MLkCSxWlZwCEFKCGw7cpU2BzU5nt

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

#Cargamos el modelo
import pickle
filename = 'modelo-reg-BEKP.pkl'
model_rn, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#Cargamos datos futuros
#data = pd.read_excel("Test_BEKP.xlsx")
#data

#interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos


st.title('Predicción de precios de pulpa BEKP')

TTO_BHKP_CH = st.slider('TTO_BHKP_CH', min_value=400, max_value=1500, value=600, step=5)
RISI_BSKP = st.slider('RISI_BSKP', min_value=400, max_value=2500, value=600, step=5)
RISI_LPSBS = st.slider('RISI_LPSBS', min_value=100, max_value=500, value=200, step=5)
RISI_OCC = st.slider('RISI_OCC', min_value=10, max_value=300, value=50, step=5)
INV_BHKP = st.slider('INV_BHKP', min_value=20, max_value=100, value=40, step=2)
INV_BSKP = st.slider('INV_BSKP', min_value=20, max_value=80, value=40, step=2)
SHIP_BHKP = st.slider('SHIP_BHKP', min_value=1000, max_value=4000, value=2000, step=20)
SHIP_BSKP = st.slider('SHIP_BSKP', min_value=1000, max_value=3000, value=2000, step=20)
CPI_USA = st.slider('CPI_USA', min_value=-0.2, max_value=0.2, value=0.1, step=0.05)
IRATE_USA = st.slider('IRATE_USA', min_value=-0.05, max_value=0.1, value=0.1, step=0.05)


#Dataframe
datos = [[TTO_BHKP_CH,RISI_BSKP,RISI_LPSBS,RISI_OCC,
INV_BHKP,INV_BSKP,SHIP_BHKP,SHIP_BSKP,CPI_USA,IRATE_USA]]
data = pd.DataFrame(datos, columns=variables) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()
data_preparada.head()

#Se normalizan los datos
#En los despliegues no se llama fit

data_preparada[variables] = min_max_scaler.transform(data_preparada[variables])
data_preparada.head()

"""## **PREDICCIONES**"""

#Hacemos la predicción con las NN
Y_pred = model_rn.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 8%")